server:
  port: 8080
logging:
  config: src/main/resources/log4j.properties


spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/test
     username: root
     password: choice
     driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8


mybatis:
     mapperLocations: classpath:mapper/*.xml
     type-aliases-package: com.example.interfacetest.entity

mapper:
     mappers: com.example.interfacetest.dao
     not-empty: false
     identity: MYSQL

